git-writebackup-import: Usability: Mention missing path/to/srcdir in error message

diff --git a/bin/git-writebackup-import b/bin/git-writebackup-import
--- a/bin/git-writebackup-import
+++ b/bin/git-writebackup-import
@@ -218,7 +218,12 @@ do
 	*)		break;;
     esac
 done
-[ $# -ne 1 ] && { printUsage "$0" >&2; exit 2; }
+if [ $# -ne 1 ]; then
+    echo 'ERROR: No path/to/srcdir passed.'
+    echo
+    printUsage "$0"
+    exit 2
+fi >&2
 readonly srcdir="${1%/}/"
 
 git status >/dev/null || exit $?
