writebackup: Cosmetics: Quote files with single quotes
And turn the ! into a .
And fix one missing \n.

diff --git a/bin/writebackup b/bin/writebackup
--- a/bin/writebackup
+++ b/bin/writebackup
@@ -138,7 +138,7 @@ elif [ "$isOnlyPrintExtension" ] && [ "$isDeleteOriginal" ]; then
     exit 3
 elif [ -n "$backupDir" -a ! -d "$backupDir" ]; then
     backupDir="${backupDir%/}"
-    printf 'ERROR: Backup dir does not exist: "%s"!\n' "${backupDir:-/}"
+    printf 'ERROR: Backup dir does not exist: %s\n' "${backupDir:-/}"
     exit 3
 fi >&2
 
@@ -182,7 +182,7 @@ archiveAndBackup()
 	    printBackupFile "${backupDir:-${baseDirspec}/}$(basename -- "${backupFilespec}")"
 	    popd >/dev/null || :
 	} || {
-	    echo >&2 'Could not create archive!'
+	    echo >&2 'ERROR: Could not create archive.'
 	    popd >/dev/null || :
 	    return 1
 	}
@@ -231,7 +231,7 @@ getBackupFilename()
     done
 
     # All backup letters a-z are already used; do not return a backup filename.
-    printf >&2 'Ran out of backup file names for file "%s"!\n' "$filespec"
+    printf >&2 "Ran out of backup file names for file '%s'.\\n" "$filespec"
     return 1
 }
 
@@ -253,7 +253,7 @@ writebackup()
 
     if [ -f "${spec}" ]; then
 	if [ ! -r "${spec}" ]; then
-	    printf >&2 'ERROR: "%s" is not readable!\n' "$spec"
+	    printf >&2 "ERROR: '%s' is not readable.\n" "$spec"
 	    return 1
 	fi
 
@@ -284,7 +284,7 @@ writebackup()
 	fi
     elif [ -d "${spec}" ]; then
 	if [ ! -r "${spec}" -o ! -x "${spec}" ]; then
-	    printf >&2 'ERROR: "%s" is not accessible!' "$spec"
+	    printf >&2 "ERROR: '%s' is not accessible.\\n" "$spec"
 	    return 1
 	fi
 	archiveAndBackup "${spec}" || return 1
@@ -297,7 +297,7 @@ writebackup()
 	local backupFilespec; backupFilespec=$(getBackupFilename "${backupTemplate}") || return $?
 	[ -n "${backupFilespec}" ] && printf '%s\n' ".${backupFilespec##*.}"
     else
-	printf >&2 'ERROR: "%s" does not exist!\n' "$spec"
+	printf >&2 "ERROR: '%s' does not exist.\\n" "$spec"
 	return 1
     fi
 }
