Extend the help into long and short variants

diff --git a/bin/writebackup b/bin/writebackup
--- a/bin/writebackup
+++ b/bin/writebackup
@@ -7,27 +7,6 @@
 # DATE CREATED:	10-Jul-2003
 #
 ###############################################################################
-# CONTENTS:
-#   Write subsequent backups of passed file(s) with a current date file
-#   extension (format '.YYYYMMDD[a-z]') in the same directory as the file
-#   itself. The first backup of a day has letter 'a' appended, the next 'b', and
-#   so on. (Which means that a file can be backed up up to 26 times on any given
-#   day.)
-#   Directories will be zipped (individually) into an archive file with date
-#   file extension. For example, a directory 'foo' will be backed up to
-#   'foo.zip.20070911a'. This zip file will only contain the 'foo' directory at
-#   its top level; 'foo' itself will contain the entire subtree of the original
-#   'foo' directory.
-#   The archiver can be changed; e.g. you could use 'tar' instead of 'zip' by
-#   specifying
-#	--archive-program "tar cvf" --archive-extension .tar
-#
-# DIAGNOSTICS:
-#   0	Complete success.
-#   1	Failed to backup any file(s).
-#   2	Partial success; some file(s) could not be backed up.
-#   3	Bad invocation, wrong or missing command-line arguments.
-#
 # REMARKS:
 #
 # DEPENDENCIES:
@@ -44,6 +23,7 @@
 # REVISION	DATE		REMARKS
 #   1.40.008	29-Dec-2018	ENH: Allow to do only a single backup each day
 #				via --once-today.
+#				Extend the help into long and short variants.
 #   1.30.007	09-Sep-2017	ENH: Allow to remove the original file via
 #				--delete-original.
 #   1.20.006	13-Apr-2012	ENH: Allow different backup directory via
@@ -205,9 +185,22 @@ writebackup()
     fi
 }
 
+printShortUsage()
+{
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--archive-program \"zip -9 -r\" --archive-extension .zip] [--backup-dir|-d DIR] [--delete-original] [--once-today] FILE [...] [--help|-h|-?]'
+}
 printUsage()
 {
-    cat <<HELPTEXT
+    # This is the short help when launched with no or incorrect arguments.
+    # It is printed to stderr to avoid accidental processing.
+    printShortUsage "$1" >&2
+    printf 'Try %q %s\n' "$(basename "$1")" '--help for more information.'
+}
+printLongUsage()
+{
+    # This is the long "man page" when launched with the help argument.
+    # It is printed to stdout to allow paging with 'more'.
+    cat <<HELPDESCRIPTION
 This is a poor man's revision control system, a primitive alternative to CVS,
 RCS, Subversion, etc., which works with no additional software and almost any
 file system.
@@ -222,13 +215,27 @@ extension. For example, a directory 'foo' will be backed up to
 'foo.zip.20070911a'. This zip file will only contain the 'foo' directory at its
 top level; 'foo' itself will contain the entire subtree of the original 'foo'
 directory.
-The archiver can be changed with --archive-program and --archive-extension.
-With --delete-original, the original file is removed; you can use this for a
-final backup before getting rid of the file.
-With --once-today, a FILE is only backed up if no backup on the current day was
-already made.
+HELPDESCRIPTION
+    echo
+    printShortUsage "$1"
+    cat <<HELPTEXT
+    --archive-program ARCHIVER-COMMAND
+				Use a different archive program; e.g. you could
+				use 'tar' instead of 'zip' by specifying
+				--archive-program "tar cvf"
+				--archive-extension .tar
+    --archive-extension EXT	Configure the archive extension for a custom
+				archiver.
+    --delete-original		Removes the original file; you can use this for
+				a final backup before getting rid of the file.
+    --once-today		A FILE is only backed up if no backup on the
+				current day was already made.
+EXIT STATUS:
+    0	Complete success.
+    1	Failed to backup any file(s).
+    2	Partial success; some file(s) could not be backed up.
+    3	Bad invocation, wrong or missing command-line arguments.
 HELPTEXT
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--archive-program \"zip -9 -r\" --archive-extension .zip] [--backup-dir|-d DIR] [--delete-original] [--once-today] FILE [...] [--help|-h|-?]'
 }
 
 #------------------------------------------------------------------------------
@@ -240,11 +247,11 @@ isOnceToday=
 while [ $# -ne 0 ]
 do
     case "$1" in
-	--help|-h|-\?)		shift; printUsage "$0"; exit 0;;
+	--help|-h|-\?)		shift; printLongUsage "$0"; exit 0;;
 	--archive-program)	shift; archiveProgram="$1"; shift;;
 	--archive-extension)	shift; archiveExtension="$1"; shift;;
 	--backup-dir|-d)	if [ -z "$2" ]; then
-				    { echo "ERROR: Must pass directory after ${1}!"; echo; printUsage "$0"; } >&2
+				    { echo "ERROR: Must pass directory after ${1}!"; echo; printShortUsage "$0"; } >&2
 				    exit 3
 				fi
 				shift
