ENH: Allow to do only a single backup each day via --once-today

diff --git a/bin/writebackup b/bin/writebackup
--- a/bin/writebackup
+++ b/bin/writebackup
@@ -34,14 +34,16 @@
 #   - cp, dc
 #   - for archives: readlink, zip (or other archive tool)
 #
-# Copyright: (C) 2007-2012 Ingo Karkat
+# Copyright: (C) 2007-2018 Ingo Karkat
 #   This program is free software; you can redistribute it and/or modify it
 #   under the terms of the GNU General Public License.
 #   See http://www.gnu.org/copyleft/gpl.txt
 #
-# FILE_SCCS = "@(#)writebackup	1.30.007	(09-Sep-2017)	tools";
+# FILE_SCCS = "@(#)writebackup	1.40.008	(29-Dec-2018)	tools";
 #
 # REVISION	DATE		REMARKS
+#   1.40.008	29-Dec-2018	ENH: Allow to do only a single backup each day
+#				via --once-today.
 #   1.30.007	09-Sep-2017	ENH: Allow to remove the original file via
 #				--delete-original.
 #   1.20.006	13-Apr-2012	ENH: Allow different backup directory via
@@ -124,7 +126,13 @@ getBackupFilename()
 	local numberchar=$(echo ${number}P|dc)
 	local backupFilespec="${filespec}.${timestamp}${numberchar}"
 	if [ -a "${backupFilespec}" ]; then
-	    # Current backup letter already exists, try next one.
+	    # Current backup letter already exists.
+	    if [ "$isOnceToday" ]; then
+		# A backup for today already exists; don't do another one.
+		return 1
+	    fi
+
+	    # Try next backup letter.
 	    let number+=1
 	    continue
 	fi
@@ -199,13 +207,35 @@ writebackup()
 
 printUsage()
 {
-    echo >&2 "Usage: \"$(basename "$1")\" [--archive-program \"zip -9 -r\" --archive-extension .zip] [--backup-dir|-d <dir>] [--delete-original] <file> [,...] [--help|-h|-?]"
+    cat <<HELPTEXT
+This is a poor man's revision control system, a primitive alternative to CVS,
+RCS, Subversion, etc., which works with no additional software and almost any
+file system.
+Writes subsequent backups of the current file with a 'current date + counter'
+file extension (format '.YYYYMMDD[a-z]'). The first backup of a day has letter
+'a' appended, the next 'b', and so on. (So that a file can be backed up up to 26
+times on any given day.)
+By default, backups are created in the same directory as the original file; you
+can specify a different directory via -d|--backup-dir.
+Directories will be zipped (individually) into an archive file with date file
+extension. For example, a directory 'foo' will be backed up to
+'foo.zip.20070911a'. This zip file will only contain the 'foo' directory at its
+top level; 'foo' itself will contain the entire subtree of the original 'foo'
+directory.
+The archiver can be changed with --archive-program and --archive-extension.
+With --delete-original, the original file is removed; you can use this for a
+final backup before getting rid of the file.
+With --once-today, a FILE is only backed up if no backup on the current day was
+already made.
+HELPTEXT
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--archive-program \"zip -9 -r\" --archive-extension .zip] [--backup-dir|-d DIR] [--delete-original] [--once-today] FILE [...] [--help|-h|-?]'
 }
 
 #------------------------------------------------------------------------------
 
 backupDir=
 isDeleteOriginal=
+isOnceToday=
 
 while [ $# -ne 0 ]
 do
@@ -222,17 +252,18 @@ do
 				shift
 				;;
 	--delete-original)	shift; isDeleteOriginal=t;;
+	--once-today)		shift; isOnceToday=t;;
 	--)			shift; break;;
 	-*)			{ echo "ERROR: Unknown option \"${1}\"!"; echo; printUsage "$0"; } >&2; exit 3;;
 	*)			break;;
     esac
 done
 if [ $# -eq 0 ]; then
-    printUsage "$0"
+    printUsage "$0" >&2
     exit 3
 fi
 if [ "$backupDir" -a ! -d "${backupDir%/}" ]; then
-    echo "ERROR: Backup dir does not exist: \"${backupDir%/}\"!"
+    echo >&2 "ERROR: Backup dir does not exist: \"${backupDir%/}\"!"
     exit 3
 fi
 
